name: simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
      ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      IMAGE_TAG: weveryone_bot:$(date +%s)
jobs:

  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag "${IMAGE_TAG}"
  deploy:
    needs: build 
    runs-on: self-hosted
    env:
      ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker run weveryone_bot:latest
