name: simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: weveryone_bot:$(date +%s)

jobs:   
  
  build:
    runs-on: self-hosted
    steps:
    - name: deep cleanup
      run: docker system prune -a -f
    - name: build image
      run: docker build . -t weveryone_bot
      
  deploy:
    needs: build 
    runs-on: self-hosted
    env:
      ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      ENVIRONMENT: "PROD"
    steps:
    - uses: actions/checkout@v3

    - name: deploy
      run: docker run -d -e BOT_TOKEN=${ADMIN_TELEGRAM_ID} -e BOT_TOKEN=${BOT_TOKEN} weveryone_bot:latest
