name: simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
env:
  IMAGE_NAME: weveryone_bot:$(date +%s)

jobs:
  create_blank_env_file:
    runs-on: self-hosted
    steps:
    - name: create empty env file
      run: touch .env 
  
  build:
    needs: create_blank_env_file
    runs-on: self-hosted
    steps:
    - name: deep cleanup
      run: docker system prune -a -f
    - name: build image
      run: docker build . -t ${{ env.IMAGE_NAME }}
      
  deploy:
    needs: ["create_blank_env_file", "build"] 
    runs-on: self-hosted
    env:
      ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: deploy
      run: docker run weveryone_bot:latest
