name: simple CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  cleanup:
    runs-on: self-hosted
    steps:
    - name: down containers
      run: docker compose -f prod.docker-compose.yml down
    - name: deep cleanup
      run: docker system prune -a -f
      
  deploy:
    needs: cleanup 
    runs-on: self-hosted
    env:
      ADMIN_TELEGRAM_ID: ${{ secrets.ADMIN_TELEGRAM_ID }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - name: deploy
      run: docker compose -f prod.docker-compose.yml up -d
